name: Notify Telegram Users

on:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов
  workflow_dispatch: # Позволяет запускать вручную через интерфейс Гитхаба

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install firebase-admin --legacy-peer-deps

    - name: Run notification script
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: node scripts/check-discounts.mjs
